name: DEPLOY
on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.2.0
      with:
        hugo-version: '0.69.0'
        extended: true
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    
    - name: Build
      run: hugo --gc --minify --cleanDestinationDir -b "https://www.liangzhili.com"
    
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.0
      with:
        switches: -avzr --delete --exclude-from 'rsync-exclude-list.txt'
        path: public
        remote_path: ${{ secrets.REMOTE_PATH }}
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_port: ${{ secrets.DEPLOY_PORT }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
